language: node_js
node_js:
- '6'
before_install:
- npm install istanbul mocha babel-preset-es2015 -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
